name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files and Directory
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@master
        with: 
          who-to-greet: My future Me
      - name: Log greeting Time
        run:  echo "${{ steps.greet.outputs.time }}"

